### PR TITLE
NEXUS-8449 - Update jetty xml configuration options as it pertains to https

### PR DESCRIPTION
**Pull request by peterlynch**
Depends on https://github.com/sonatype/nexus-internal/pull/333

### CODE REVIEW

**Comment by mosabua** [comment]
As agreed with @peterlynch I will review, merge and add a generic section about usage of NEXUS_HOME ... no other reviews necessary at this stage.

**Comment by peterlynch** [comment]
@mosabua somewhat related, this is what I believe is a concise and clear outline of important directory terms with regards to Nexus 2

https://support.sonatype.com/hc/en-us/articles/213464308-Understanding-Nexus-Installation-Directories

**Comment by mosabua** [comment]
Following that guide assumes that there is a shared top level nexus directory in which you find the application and the data (sonatype-work). From what I have seen this is often not the case and certainly not required.

**Comment by mosabua** [comment]
I will also have to check what names are used in the installer to be consistent..

**Comment by peterlynch** [comment]
lets not let the NEXUS_HOME related changes block this PR

**Comment by mosabua** [comment]
I am not... I just got a lot of other things to do as well and we cant publish this whole set for a bit anyway. I am going to merge and update this all today.

**Pull request merged**
