### PR TITLE
Json format fix

### PR DESCRIPTION
**Pull request by dulanism**
added quotes around keys, changed to curly brackets

### CODE REVIEW

**Comment by dulanism** [comment]
PR created to make sure this format (JSON) can be properly parsed with Groovy JsonSlurper class, as noted by @bradbeck.

**Comment by mosabua** [comment]
Well... the original one was tested to be working. If you change it.. you have to verify that the new markup works. It should.. but its up to you to ensure that @dulanism

**Comment by kellyrob99** [comment]
+1, tested and works

**Comment by mosabua** [comment]
Thanks for verifying @kellyrob99 ... then I am +1 as well .

Btw @dulanism  ... when you change docs in the scripting chapter you potentially also need to fix/adapt/test the actual scripts. They can be found here https://github.com/sonatype/nexus-book-examples/tree/nexus-3.0.x/scripting and are linked from the docs.

**Pull request merged**
