### PR TITLE
fix hidden anchor link titles

### PR DESCRIPTION
**Pull request by peterlynch**
An example url:

http://books.sonatype.com/nexus-book/3.0/reference/security.html#ssl-inbound

Before:

image

After:

image

### CODE REVIEW

**Comment by joedragons** [comment]
Nice, that's bugged me for a while.

**Comment by peterlynch** [comment]
Please apply this to the other Nexus 2.x branches as needed.

**Comment by mosabua** [comment]
This is awesome @peterlynch .. I will roll this into all the branches for the 2.12 and rebranding roll out. 

@jwayman and @annrollo should port this over to the Nexus IQ Server documentation as well.

**Comment by mosabua** [comment]
Btw @jwayman .. you should include that in a commit that does the navigation refactor across branches.. that way you can cherry pick across easily and do it in one sweep. I am just doing it for 2.8+ here now.

**Pull request merged**
