### PR TITLE
Quick fix osvdb sentence

### PR DESCRIPTION
**Pull request by dulanism**
Quick change to the sentence to make more sense. This is for the Kaos team.
https://issues.sonatype.org/browse/CLM-6018

Associated edits:
http://bamboo.s/browse/BOOK-NEXUS2-234
http://bamboo.s/browse/BOOK-NEXUS-388

### CODE REVIEW

**Comment by bentmann** [comment]
+1

Unclear which team is supposed to review/approve this but since it shows up on my board... Also odd to see a PR after the meat of the changes were already committed to master.

**Comment by dulanism** [comment]
@bentmann This is for Kaos. This was a last minute cross-team assigned by @jwayman and @basil3whitehouse. Sorry for the confusion. Updated the PR to include JIRA story

**Comment by vladt** [comment]
+1 Looks ok to me.

**Comment by DennisWarren** [comment]
+1 Looks good.

**Pull request merged**
