### PR TITLE
Fixed path to Nexus binary in the systemd service

### PR DESCRIPTION
**Pull request by wikier**

### CODE REVIEW

**Comment by dulanism** [comment]
@wikier Just making sure that I follow you. Did you create the `nexus.service` file and add it to `/etc/systemd/system` before running the service from `/opt/nexus/bin`?

**Comment by wikier** [comment]
Yes, i did @dulanism. But then I got the error that {{ExecStart}} was invalid, that's the purpose of this fix to the documentation. The change has been used, and it's working, on my dev environment.

**Comment by dulanism** [comment]
Thank you, @wikier. The book is updated.

**Comment by wikier** [comment]
Perfect. Thanks, @dulanism.

**Pull request closed without merging**
