### PR TITLE
dulanism-patch-empty-group-upgrade

### PR DESCRIPTION
**Pull request by dulanism**
From https://github.com/sonatype/nexus-internal/pull/937 (already merged)

### CODE REVIEW

**Comment by fjmilens3** [comment]
+1 here, makes sense to me to get this covered.

**Comment by joedragons** [comment]
Defer to @fjmilens3 as I haven't seen this in action=)

**Comment by dulanism** [comment]
Back to WIP, while being tested.

**Comment by joedragons** [comment]
+1.  I was going to suggest more specifics as to behavior when migrating but that's not appropriate for the section you've changed.  I think this is solid.  Thanks!

**Comment by dulanism** [comment]
I left his pending as WIP, to re-write/add-on accordingly. But if this is cool, I'll merge it. Thx @joedragons & @fjmilens3

**Pull request merged**
