### PR TITLE
Removes duplicated words from asciidoc files ( fixes issue #146 )

### PR DESCRIPTION
**Pull request by lsolano**
There are multiple repeated words in the `asciidoc` files. Use the regex `\b(\w+)\s+\1\b` to find the typos.

### CODE REVIEW

**Comment by joedragons** [comment]
+1

**Comment by dulanism** [comment]
Thanks @lsolano

**Comment by mosabua** [comment]
Too funny that there were so many. Thanks @lsolano

**Comment by lsolano** [comment]
My pleasure.

**Pull request merged**
