### PR TITLE
Typo fixes

### PR DESCRIPTION
**Pull request by joedragons**
On scan of new section (RE: NEXUS-9757).
I am confident the above are typos but not 100% confident that my fixes are correct so making a PR rather than just merging.  Would appreciate a +1.

### CODE REVIEW

**Comment by dulanism** [comment]
+1 for grammatical fixes... though exempli gratia should be abbreviated as "e.g." not "E.g."

**Comment by mrprescott** [comment]
+1

**Comment by joedragons** [comment]
@dulanism This is done a lot through our documentation, so I think that's a bigger effort.  I rarely use those abbrevs myself, but I know E.e. was wrong=)  Thanks!

**Comment by mosabua** [comment]
Latin has uppercase at the beginning of the sentence just like English, German and many other languages. 

http://english.stackexchange.com/questions/28172/when-a-sentence-starts-with-e-g-should-the-e-be-capitalized

Also using e.g. is okay as part of our style guide. But you can use "for example" as well.

**Comment by mosabua** [comment]
Thanks for those fixes btw.

**Pull request merged**
